---
devices:
  samplerate: 48000
  chunksize: 1024
  enable_rate_adjust: true
  enable_resampling: true
  resampler_type: AccurateAsync
  capture_samplerate: 48000
  capture:
    type: Alsa
    channels: 32
    device: "input_cards"
    format: S32LE
  playback:
    type: Alsa
    channels: 48
    device: "output_cards"
    format: S32LE
    
mixers:
  to48chan:
    channels:
      in: 32
      out: 48
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -3
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: -3
            inverted: false
      - dest: 2
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 3
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 4
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 5
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 6
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 7
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 8
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 9
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 10
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 11
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 12
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 13
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 14
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 15
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 16
        sources:
          - channel: 0
            gain: -3
            inverted: false
      - dest: 17
        sources:
          - channel: 1
            gain: -3
            inverted: false
      - dest: 18
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 19
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 20
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 21
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 22
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 23
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 24
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 25
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 26
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 27
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 28
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 29
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 30
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 31
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 32
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 33
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 34
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 35
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 36
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 37
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 38
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 39
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 40
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 41
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 42
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 43
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 44
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 45
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 46
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 47
        sources:
          - channel: 1
            gain: 0
            inverted: false

filters:
  highpass1:
    type: Biquad
    parameters:
      type: Highpass
      freq: 60
      q: 0.54
  highpass2:
    type: Biquad
    parameters:
      type: Highpass
      freq: 60
      q: 1.31
  highpass3:
    type: Biquad
    parameters:
      type: Highpass
      freq: 60
      q: 0.71
  lowpass1:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 60
      q: 0.54
  lowpass2:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 60
      q: 1.31
  delay:
    type: Delay
    parameters:
      delay: 30
      unit: ms
      subsample: false

pipeline:
  - type: Mixer
    name: to48chan
  - type: Filter
    channel: 0
    names:
      - highpass1
      - highpass2
      - delay
  - type: Filter
    channel: 1
    names:
      - highpass1
      - highpass2
      - delay
  - type: Filter
    channel: 16
    names:
      - lowpass1
      - lowpass2
      - lowpass1
      - lowpass2
  - type: Filter
    channel: 17
    names:
      - lowpass1
      - lowpass2
      - lowpass1
      - lowpass2