---
devices:
  samplerate: 48000
  chunksize: 4096
  enable_rate_adjust: false
  enable_resampling: true
  resampler_type: AccurateAsync
  capture_samplerate: 44100
  capture:
    type: Alsa
    channels: 16
    device: "input_card1"
    format: S32LE
  playback:
    type: Alsa
    channels: 48
    device: "output_card2"
    format: S32LE
    
mixers:
  to48chan:
    channels:
      in: 16
      out: 48
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -3
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: -3
            inverted: false
      - dest: 2
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 3
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 4
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 5
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 6
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 7
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 8
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 9
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 10
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 11
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 12
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 13
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 14
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 15
        sources:
          - channel: 1
            gain: 0
            inverted: false

filters:
  delay:
    type: Delay
    parameters:
      delay: 30
      unit: ms
      subsample: false

pipeline:
  - type: Mixer
    name: to48chan
