---
devices:
  samplerate: 48000
  chunksize: 1024
  enable_rate_adjust: false
  enable_resampling: false
  resampler_type: AccurateAsync
  capture_samplerate: 48000
  capture:
    type: Alsa
    channels: 16
    device: "input_card2"
    format: S32LE
  playback:
    type: Alsa
    channels: 16
    device: "output_card1"
    format: S32LE
     
mixers:
  2to8:
    channels:
      in: 16
      out: 16
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: -6
            inverted: false
      - dest: 2
        sources:
          - channel: 0
            gain: -6
            inverted: false
      - dest: 3
        sources:
          - channel: 1
            gain: -6
            inverted: false
      - dest: 4
        sources:
          - channel: 0
            gain: -6
            inverted: false
      - dest: 5
        sources:
          - channel: 1
            gain: -6
            inverted: false
      - dest: 6
        sources:
          - channel: 0
            gain: -6
            inverted: false
      - dest: 7
        sources:
          - channel: 1
            gain: -6
            inverted: false

filters:
  lowpass1:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 50
      q: 0.54
  lowpass2:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 50
      q: 1.31
  lowpass3:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 500
      q: 0.71
  lowpass4:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 3000
      q: 0.71
  highpass1:
    type: Biquad
    parameters:
      type: Highpass
      freq: 50
      q: 0.71
  highpass2:
    type: Biquad
    parameters:
      type: Highpass
      freq: 500
      q: 0.71
  highpass3:
    type: Biquad
    parameters:
      type: Highpass
      freq: 3000
      q: 0.71
  eqmidb1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 160
      bandwidth: 0.25
      gain: -3
  eqmidb2:
    type: Biquad
    parameters:
      type: Peaking
      freq: 235
      bandwidth: 0.1
      gain: -6
  eqmid:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1800
      bandwidth: 0.2
      gain: -6
  eqhigh1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3500
      bandwidth: 0.1
      gain: -6
  eqhigh2:
    type: Biquad
    parameters:
      type: Peaking
      freq: 6000
      bandwidth: 0.15
      gain: -6
  delaymidbase:
    type: Delay
    parameters:
      delay: 0.33
      unit: ms
      subsample: false
  delaymid:
    type: Delay
    parameters:
      delay: 19.03
      unit: ms
      subsample: false
  delayhigh:
    type: Delay
    parameters:
      delay: 18.74
      unit: ms
      subsample: false

pipeline:
  - type: Mixer
    name: 2to8
  - type: Filter
    channel: 0 #left bass
    names:
      - lowpass1
      - lowpass2
      - lowpass1
      - lowpass2
  - type: Filter
    channel: 1 #right bass
    names:
      - lowpass1
      - lowpass2
      - lowpass1
      - lowpass2
  - type: Filter
    channel: 2 #left midbass
    names:
      - highpass1
      - highpass1
      - lowpass3
      - lowpass3
      - eqmidb1
      - eqmidb2
      - delaymidbase
  - type: Filter
    channel: 3 #right midbass
    names:
      - highpass1
      - highpass1
      - lowpass3
      - lowpass3
      - eqmidb1
      - eqmidb2
      - delaymidbase
  - type: Filter
    channel: 4 #left mids
    names:
      - highpass2
      - highpass2
      - lowpass4
      - lowpass4
      - eqmid
      - delaymid
  - type: Filter
    channel: 5 #right mids
    names:
      - highpass2
      - highpass2
      - lowpass4
      - lowpass4
      - eqmid
      - delaymid
  - type: Filter
    channel: 6 #left highs
    names:
      - highpass3
      - highpass3
      - eqhigh1
      - eqhigh2
      - delayhigh
  - type: Filter
    channel: 7 #right highs
    names:
      - highpass3
      - highpass3
      - eqhigh1
      - eqhigh2
      - delayhigh
