---
devices:
  samplerate: 48000
  chunksize: 1024
  target_level: 1024
  adjust_period: 3
  enable_rate_adjust: false
  enable_resampling: false
  resampler_type:  BalancedAsync
  capture_samplerate: 48000
  capture:
    type: Alsa
    channels: 2
    device: "input_card1"
    format: S32LE
  playback:
    type: Alsa
    channels: 48
    device: "output_cards"
    format: S32LE
     
mixers:
  mixer:
    channels:
      in: 2
      out: 48
    mapping:
      - dest: 0
        mute: false
        sources:
          - channel: 0
            gain: -3
            inverted: false
      - dest: 1
        mute: false
        sources:
          - channel: 0
            gain: -13
            inverted: true
      - dest: 2
        mute: false
        sources:
          - channel: 0
            gain: -10
            inverted: false
      - dest: 3
        mute: false
        sources:
          - channel: 0
            gain: 0
            inverted: true

      - dest: 4
        mute: false
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 5
        mute: false
        sources:
          - channel: 1
            gain: -13
            inverted: true
      - dest: 6
        mute: false
        sources:
          - channel: 1
            gain: -10
            inverted: false
      - dest: 7
        mute: false
        sources:
          - channel: 1
            gain: 0
            inverted: true

      - dest: 8
        mute: false
        sources:
          - channel: 0
            gain: -3
            inverted: false
      - dest: 9
        mute: false
        sources:
          - channel: 0
            gain: -13
            inverted: true
      - dest: 10
        mute: false
        sources:
          - channel: 0
            gain: -10
            inverted: false
      - dest: 11
        mute: false
        sources:
          - channel: 0
            gain: 0
            inverted: true

      - dest: 12
        mute: false
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 13
        mute: false
        sources:
          - channel: 1
            gain: -13
            inverted: true
      - dest: 14
        mute: false
        sources:
          - channel: 1
            gain: -10
            inverted: false
      - dest: 15
        mute: false
        sources:
          - channel: 1
            gain: 0
            inverted: true

      - dest: 16
        mute: false
        sources:
          - channel: 0
            gain: -3
            inverted: false
      - dest: 17
        mute: false
        sources:
          - channel: 0
            gain: -13
            inverted: true
      - dest: 18
        mute: false
        sources:
          - channel: 0
            gain: -10
            inverted: false
      - dest: 19
        mute: false
        sources:
          - channel: 0
            gain: 0
            inverted: true

pipeline:
  - type: Mixer
    name: mixer
  - type: Filter
    channel: 0 #left bass
    names:
      - lowpass_bass
      - delay_bass
      - volumegain
      - volume
  - type: Filter
    channel: 1 #left midbass
    names:
      - fir_midbass
      - eq_mbass
      - eq_mbass1
      - delay_midbass
      - volumegain
      - volume
  - type: Filter
    channel: 2 #left mids
    names:
      - fir_mid
      - eq_mid
      - delay_mid
      - volumegain
      - volume
  - type: Filter
    channel: 3 #left highs
    names:
      - fir_high
      - delay_high
      - volumegain
      - volume

  - type: Filter
    channel: 4 #right bass
    names:
      - lowpass_bass
      - delay_bass
      - volumegain
      - volume
  - type: Filter
    channel: 5 #right midbass
    names:
      - fir_midbass
      - eq_mbass1
      - eq_mbass
      - delay_midbass
      - volumegain
      - volume
  - type: Filter
    channel: 6 #right mids
    names:
      - fir_mid
      - eq_mid
      - delay_mid
      - volumegain
      - volume
  - type: Filter
    channel: 7 #right highs
    names:
      - fir_high
      - delay_high
      - volumegain
      - volume

  - type: Filter
    channel: 16 #left bass
    names:
      - lowpass_bass
      - delay_bass
      - volumegain
      - volume
  - type: Filter
    channel: 17 #left midbass
    names:
      - fir_midbass
      - eq_mbass
      - eq_mbass1
      - delay_midbass
      - volumegain
      - volume
  - type: Filter
    channel: 18 #left mids
    names:
      - fir_mid
      - eq_mid
      - delay_mid
      - volumegain
      - volume
  - type: Filter
    channel: 19 #left highs
    names:
      - fir_high
      - delay_high
      - volumegain
      - volume

filters:
  volumegain:
    type: Gain
    parameters:
      gain: -24.0
      inverted: false
      mute: false
  volume:
    type: Volume
    parameters:
      ramp_time: 200
  lowpass_bass:
    type: BiquadCombo
    parameters:
      type: LinkwitzRileyLowpass
      freq: 50
      order: 8
  eq_high1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3500
      q: 4
      gain: -6
  eq_mbass1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 58
      q: 8
      gain: -4
  eq_mbass:
    type: Biquad
    parameters:
      type: Peaking
      freq: 60
      q: 2
      gain: 6
  eq_mid:
    type: Biquad
    parameters:
      type: Peaking
      freq: 480
      q: 4
      gain: -4
  delay_bass:
    type: Delay
    parameters:
      delay: 102
      unit: ms
      subsample: false
  delay_midbass:
    type: Delay
    parameters:
      delay: 1.35
      unit: ms
      subsample: false
  delay_mid:
    type: Delay
    parameters:
      delay: 95.1
      unit: ms
      subsample: false
  delay_high:
    type: Delay
    parameters:
      delay: 5.0
      unit: ms
      subsample: false
  fir_midbass:
    type: Conv
    parameters:
      type: Raw
      format: TEXT
      filename: ../firs/kr.txt
  fir_mid:
    type: Conv
    parameters:
      type: Raw
      format: TEXT
      filename: ../firs/seos30k.txt 
  fir_high:
    type: Conv
    parameters:
      type: Raw
      format: TEXT
      filename: ../firs/seos10k.txt
